[Tue Jun 10 20:58:39.819323 2025] [php:error] [pid 4988:tid 1344] [client 127.0.0.1:53888] PHP Fatal error:  Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php:387) in C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php:322\nStack trace:\n#0 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Cannot modify h...', 'C:\\\\MyDevBox\\\\www...', 322)\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->{closure:Illuminate\\Foundation\\Bootstrap\\HandleExceptions::forwardsTo():255}(2, 'Cannot modify h...', 'C:\\\\MyDevBox\\\\www...', 322)\n#2 C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php(322): header('HTTP/1.1 500 In...', true, 500)\n#3 C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php(401): Symfony\\Component\\HttpFoundation\\Response->sendHeaders()\n#4 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(219): Symfony\\Component\\HttpFoundation\\Response->send()\n#5 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(196): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Illuminate\\Encryption\\MissingAppKeyException))\n#6 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Illuminate\\Encryption\\MissingAppKeyException))\n#7 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->{closure:Illuminate\\Foundation\\Bootstrap\\HandleExceptions::forwardsTo():255}(Object(Illuminate\\Encryption\\MissingAppKeyException))\n#8 {main}\n  thrown in C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php on line 322
[Tue Jun 10 20:58:40.003562 2025] [php:error] [pid 4988:tid 1344] [client 127.0.0.1:53888] PHP Fatal error:  Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php:387) in C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php:322\nStack trace:\n#0 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Cannot modify h...', 'C:\\\\MyDevBox\\\\www...', 322)\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->{closure:Illuminate\\Foundation\\Bootstrap\\HandleExceptions::forwardsTo():255}(2, 'Cannot modify h...', 'C:\\\\MyDevBox\\\\www...', 322)\n#2 C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php(322): header('HTTP/1.1 500 In...', true, 500)\n#3 C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php(401): Symfony\\Component\\HttpFoundation\\Response->sendHeaders()\n#4 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(219): Symfony\\Component\\HttpFoundation\\Response->send()\n#5 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(196): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\ErrorHandler\\Error\\FatalError))\n#6 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(232): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\ErrorHandler\\Error\\FatalError))\n#7 C:\\MyDevBox\\www\\sss\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#8 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->{closure:Illuminate\\Foundation\\Bootstrap\\HandleExceptions::forwardsTo():255}()\n#9 {main}\n  thrown in C:\\MyDevBox\\www\\sss\\vendor\\symfony\\http-foundation\\Response.php on line 322
